name: "Build Binaries"

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os.host }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Windows
            host: windows-latest

          - name: Linux
            host: ubuntu-latest

          - name: MacOS
            host: macos-11

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        if: matrix.os.host == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Building Windows
        if: matrix.os.host == 'windows-latest'
        run: |
          ffi-packages/build.bat
          bash ffi-packages/build.sh

      - name: Upload Artifacts Windows
        uses: actions/upload-artifact@v2
        if: matrix.os.host == 'windows-latest'
        with:
          name: Windows
          path: |
            ffi-packages/Clipper2/buildCP/Release/*.dll
            ffi-packages/Images/buildJP/Release/*.dll
            ffi-packages/Images/buildLG/*.dll

      - name: Building Linux
        if: matrix.os.host == 'ubuntu-latest'
        run: bash ffi-packages/build.sh -all

      - name: Upload Artifacts Linux
        uses: actions/upload-artifact@v2
        if: matrix.os.host == 'ubuntu-latest'
        with:
          name: Linux
          path: |
            ffi-packages/Clipper2/buildCP/*.so
            ffi-packages/Images/buildJP/*.so
            ffi-packages/Images/buildLG/*.so

      - name: Building MacOS
        if: matrix.os.host == 'macos-11'
        run: bash ffi-packages/build.sh -all

      - name: Upload Artifacts MacOS
        uses: actions/upload-artifact@v2
        if: matrix.os.host == 'macos-11'
        with:
          name: MacOS
          path: |
            ffi-packages/Clipper2/buildCP/*.dylib
            ffi-packages/Images/buildJP/*.dylib
            ffi-packages/Images/buildLG/*.dylib